const data = {
    "login": "jiayi-ren",
    "id": 45396888,
    "node_id": "MDQ6VXNlcjQ1Mzk2ODg4",
    "avatar_url": "https://avatars1.githubusercontent.com/u/45396888?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/jiayi-ren",
    "html_url": "https://github.com/jiayi-ren",
    "followers_url": "https://api.github.com/users/jiayi-ren/followers",
    "following_url": "https://api.github.com/users/jiayi-ren/following{/other_user}",
    "gists_url": "https://api.github.com/users/jiayi-ren/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/jiayi-ren/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/jiayi-ren/subscriptions",
    "organizations_url": "https://api.github.com/users/jiayi-ren/orgs",
    "repos_url": "https://api.github.com/users/jiayi-ren/repos",
    "events_url": "https://api.github.com/users/jiayi-ren/events{/privacy}",
    "received_events_url": "https://api.github.com/users/jiayi-ren/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Jiayi Ren",
    "company": null,
    "blog": "",
    "location": null,
    "email": null,
    "hireable": null,
    "bio": null,
    "public_repos": 45,
    "public_gists": 0,
    "followers": 7,
    "following": 12,
    "created_at": "2018-11-27T15:18:22Z",
    "updated_at": "2020-05-06T00:03:10Z"
  }

  export default data;